---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(SNFtool)
library(data.table)
library(dplyr)

rm(list= ls())

K = 25;##number of neighbors, usually (10~30)
alpha = 1.1 ##hyperparameter, usually (0.3~0.8)
T = 10; ###Number of Iterations, usually (10~20)
C = 3###number of clusters
use.corr <- F
use.shuffle <-F

gene <- data.matrix(fread("/Users/danialmalakmohammad/PycharmProjects/GVAE/GBM/GLIO_Gene_Expression.txt", header = F, sep = "\t", dec = ".")[,2:216])
methy <- data.matrix(fread("/Users/danialmalakmohammad/PycharmProjects/GVAE/GBM/GLIO_Methy_Expression.txt", header = F, sep = "\t", dec = ".")[,2:216])
mirna <- data.matrix(fread("/Users/danialmalakmohammad/PycharmProjects/GVAE/GBM/GLIO_Mirna_Expression.txt", header = F, sep = "\t", dec = ".")[,2:216])
survival <- data.matrix(fread("/Users/danialmalakmohammad/PycharmProjects/GVAE/GBM/GLIO_Survival.txt", header = F, sep = "\t", dec = ".")[-1,2])



gene = t(gene)
methy = t(methy)
mirna = t(mirna)

if (use.shuffle){
idx <- sample(1:215)
gene <- gene[idx, ]
methy <- methy[idx, ]
mirna <- mirna[idx, ]
survival <- survival[idx, ]
}



```

```{r similarity matrices calculation}

truelabel <- survival

methy = standardNormalization(methy);
gene = standardNormalization(gene);
mirna = standardNormalization(mirna);

###Calculate the pair-wise distance; If the data is continuous, we recommend to use the function "dist2" as follows; if the data is discrete, we recommend the users to use ""
if (!use.corr) {
  Dist_methy = dist2(as.matrix(methy),as.matrix(methy));
  Dist_gene = dist2(as.matrix(gene),as.matrix(gene));
  Dist_mirna = dist2(as.matrix(mirna),as.matrix(mirna));
} else {
  Dist_methy = 1 - cor(t(as.matrix(methy)));
  Dist_gene = 1 - cor(t(as.matrix(gene)));
  Dist_mirna = 1 - cor(t(as.matrix(mirna)));
}


###next, construct similarity graphs
W_methy = affinityMatrix(Dist_methy, K, alpha)
W_gene = affinityMatrix(Dist_gene, K, alpha)
W_mirna = affinityMatrix(Dist_mirna, K, alpha)

```

```{r SNF}

W = SNF(list(W_gene,W_methy,W_mirna), K, T)

```

```{r visualization}

library(corrplot)

W_tmp <- W
diag(W_tmp) <- 0

corrplot(W_tmp, is.corr = F, order = "hclust", hclust.method = "average")

```

```{r Spectral Clustering}
idx <- 1:215
Wp <- W[idx, idx]

group <- spectralClustering(Wp, 3, type = 3)
displayClusters(Wp, group)

displayClusters(W_methy, group)
displayClusters(W_gene, group)
displayClusters(W_mirna, group)
```


```{r survival classfication}
qn <- quantile(survival, probs = c(0.33, 0.66, 1))

label <- survival
  
  #(survival < qn[1]) +
  #2 * (survival < qn[2] & survival >= qn[1]) +
  #3 * (survival <= qn[3] & survival >= qn[2])
W.s <- W

W.s <- unname(W.s)

diag(W.s) <- 0
NN.indx <- apply(W.s, 1, which.max)
sum(abs(label[NN.indx] - label))/length(label)
```


```{r survival mean for classes}

# ANOVA & T-test & test from the paper 
# use ggplot2 to boxplot survival time for each group
# ss clustering (use other packages)

library(ggplot2)

p1 <- t.test(survival[group == 1], survival[group == 2])$p.value
p2 <- t.test(survival[group == 3], survival[group == 2])$p.value
p3 <- t.test(survival[group == 1], survival[group == 3])$p.value

p.adjust(c(p1, p2, p3))
c(p1, p2, p3)
#D <- data.frame(group_id = group, survival_time = survival) 
#ggplot(D, aes(x = group_id, y = survival_time)) + geom_violin(aes(group = group_id))
  
```